// Generated by CoffeeScript 1.6.3
/*

  tell

  2013 (c) Andrey Popp <8mayday@gmail.com>
*/

var Router, Stack, asPromise, createServer, http, makeURIPartRe, overlay, reject, resolve, router, stack, toHandler, _ref, _ref1,
  __slice = [].slice,
  __hasProp = {}.hasOwnProperty,
  __extends = function(child, parent) { for (var key in parent) { if (__hasProp.call(parent, key)) child[key] = parent[key]; } function ctor() { this.constructor = child; } ctor.prototype = parent.prototype; child.prototype = new ctor(); child.__super__ = parent.prototype; return child; };

http = require('http');

_ref = require('kew'), resolve = _ref.resolve, reject = _ref.reject;

createServer = function(handler) {
  return http.createServer(function(req, res) {
    return handler(null, req, res, resolve).then(function() {
      return res.end().end();
    });
  });
};

asPromise = function() {
  var args, err, func;
  func = arguments[0], args = 2 <= arguments.length ? __slice.call(arguments, 1) : [];
  try {
    return resolve(func.apply(null, args));
  } catch (_error) {
    err = _error;
    return reject(err);
  }
};

toHandler = function(h) {
  if (h.toHandler != null) {
    return h.toHandler();
  } else {
    return h;
  }
};

makeURIPartRe = function(pattern) {
  if (pattern[0] !== '/') {
    pattern = "/" + pattern;
  }
  return RegExp("^" + pattern + "(/|$)");
};

overlay = function(obj, attrs) {
  var k, newObj, v;
  newObj = Object.create(obj);
  for (k in attrs) {
    v = attrs[k];
    newObj[k] = v;
  }
  return newObj;
};

Stack = (function() {
  function Stack(handlers) {
    if (handlers == null) {
      handlers = [];
    }
    this.handlers = handlers;
  }

  Stack.prototype.use = function(handler) {
    this.handlers.push({
      onSuccess: toHandler(handler)
    });
    return this;
  };

  Stack.prototype["catch"] = function(handler) {
    this.handlers.push({
      onError: toHandler(handler)
    });
    return this;
  };

  Stack.prototype.listen = function() {
    var args, _ref1;
    args = 1 <= arguments.length ? __slice.call(arguments, 0) : [];
    return (_ref1 = createServer(this.toHandler())).listen.apply(_ref1, args);
  };

  Stack.prototype.toHandler = function() {
    return this.handle.bind(this);
  };

  Stack.prototype.handle = function(err, req, res, next) {
    var handlers, nextHandler, process;
    handlers = this.handlers.slice(0);
    nextHandler = function(name) {
      var handler;
      while (handlers.length > 0) {
        handler = handlers.shift();
        if (handler[name]) {
          return handler[name];
        }
      }
    };
    process = function(err, result) {
      var callNext, handled, handler, nextIsCalled;
      nextIsCalled = false;
      callNext = function(err, result) {
        nextIsCalled = true;
        return process(err, result);
      };
      handler = nextHandler(err ? 'onError' : 'onSuccess');
      if (!handler) {
        if (next != null) {
          return asPromise(next, err, result);
        } else {
          if (err) {
            return reject(err);
          } else {
            return resolve(result);
          }
        }
      } else {
        handled = handler.length === 4 ? asPromise(handler, err, req, res, callNext) : asPromise(handler, req, res, callNext);
        return handled.then(function(result) {
          if (nextIsCalled) {
            return result;
          } else {
            return callNext(null, result);
          }
        }).fail(function(err) {
          if (nextIsCalled) {
            throw err;
          } else {
            return callNext(err);
          }
        });
      }
    };
    return process(err);
  };

  return Stack;

})();

Router = (function(_super) {
  __extends(Router, _super);

  function Router() {
    _ref1 = Router.__super__.constructor.apply(this, arguments);
    return _ref1;
  }

  Router.prototype.use = function(pattern, handler) {
    var wrapperHandler;
    if (handler) {
      if (!(pattern instanceof RegExp)) {
        pattern = makeURIPartRe(pattern);
      }
      wrapperHandler = function(req, res, next) {
        var m, newUrl;
        m = pattern.exec(req.url);
        if (m) {
          newUrl = req.url.substring(m[0].length);
          if (newUrl[0] !== '/') {
            newUrl = "/" + newUrl;
          }
          req = overlay(req, {
            url: newUrl
          });
          return handler(req, res, next);
        } else {
          return next();
        }
      };
      return Router.__super__.use.call(this, wrapperHandler);
    } else {
      handler = pattern;
      return Router.__super__.use.call(this, handler);
    }
  };

  return Router;

})(Stack);

stack = function() {
  return new Stack;
};

router = function() {
  return new Router;
};

module.exports = {
  createServer: createServer,
  Stack: Stack,
  stack: stack,
  Router: Router,
  router: router
};
