// Generated by CoffeeScript 1.6.3
/*

  tell specs

  2013 (c) Andrey Popp <8mayday@gmail.com>
*/

var eq, ok, reject, resolve, tell, throws, throwsFlip, _ref, _ref1;

_ref = require('kew'), resolve = _ref.resolve, reject = _ref.reject;

_ref1 = require('assert'), ok = _ref1.ok, throwsFlip = _ref1.throws, eq = _ref1.equal;

tell = require('./index');

throws = function(error, block) {
  return throwsFlip(block, error);
};

describe('Tell', function() {
  it('works as a middleware tell', function(done) {
    var app, trace;
    trace = [];
    app = tell().use(function(req, res, next) {
      ok(req.req);
      ok(res.res);
      trace.push(0);
      return next();
    }).use(function(req, res, next) {
      ok(req.req);
      ok(res.res);
      trace.push(1);
      return 'ok';
    });
    return app.handle(null, {
      req: true
    }, {
      res: true
    }).then(function(res) {
      eq(res, 'ok');
      eq(trace.length, 2);
      eq(trace[0], 0);
      return eq(trace[1], 1);
    }).then(done).end();
  });
  it('automatically calls next handler if no explicit call was made', function(done) {
    var app, trace;
    trace = [];
    app = tell().use(function(req, res, next) {
      ok(req.req);
      ok(res.res);
      return trace.push(0);
    }).use(function(req, res, next) {
      ok(req.req);
      ok(res.res);
      trace.push(1);
      return 'ok';
    });
    return app.handle(null, {
      req: true
    }, {
      res: true
    }).then(function(res) {
      eq(res, 'ok');
      eq(trace.length, 2);
      eq(trace[0], 0);
      return eq(trace[1], 1);
    }).then(done).end();
  });
  it('handles empty tell', function(done) {
    var app;
    app = tell();
    return app.handle(null, {
      req: true
    }, {
      res: true
    }).then(function(res) {
      return eq(res, void 0);
    }).then(done).end();
  });
  it('allows delegating to sub-tells', function(done) {
    var app, trace;
    trace = [];
    app = tell().use(function(req, res, next) {
      ok(req.req);
      ok(res.res);
      return trace.push(0);
    }).use(tell().use(function(req, res, next) {
      ok(req.req);
      ok(res.res);
      return trace.push(1);
    }).use(function(req, res, next) {
      ok(req.req);
      ok(res.res);
      trace.push(2);
      return 'ok';
    }));
    return app.handle(null, {
      req: true
    }, {
      res: true
    }).then(function(res) {
      eq(res, 'ok');
      eq(trace.length, 3);
      eq(trace[0], 0);
      eq(trace[1], 1);
      return eq(trace[2], 2);
    }).then(done).end();
  });
  it('propagates thrown error to top level', function() {
    var app;
    app = tell().use(function(req, res, next) {
      throw new Error('error');
    });
    return throws(Error, function() {
      return app.handle(null, {
        req: true
      }, {
        res: true
      }).fail(function(err) {
        ok(err);
        throw err;
      }).end();
    });
  });
  it('propagates rejected promise to top level', function() {
    var app;
    app = tell().use(function(req, res, next) {
      return reject(new Error('error'));
    });
    return throws(Error, function() {
      return app.handle(null, {
        req: true
      }, {
        res: true
      }).fail(function(err) {
        ok(err);
        throw err;
      }).end();
    });
  });
  it('propagates passed error to top level', function() {
    var app;
    app = tell().use(function(req, res, next) {
      return next(new Error('error'));
    });
    return throws(Error, function() {
      return app.handle(null, {
        req: true
      }, {
        res: true
      }).fail(function(err) {
        ok(err);
        throw err;
      }).end();
    });
  });
  it('catches thrown error with a handler', function(done) {
    var app, trace;
    trace = [];
    app = tell().use(function(req, res, next) {
      throw new Error('error');
    })["catch"](function(err, req, res, next) {
      ok(req.req);
      ok(res.res);
      ok(err);
      return trace.push(1);
    }).use(function(req, res, next) {
      ok(req.req);
      ok(res.res);
      trace.push(2);
      return 'ok';
    });
    return app.handle(null, {
      req: true
    }, {
      res: true
    }).then(function(res) {
      eq(res, 'ok');
      return eq(trace.length, 2);
    }).then(done).end();
  });
  it('catches rejected promise with a handler', function(done) {
    var app, trace;
    trace = [];
    app = tell().use(function(req, res, next) {
      return reject(new Error('error'));
    })["catch"](function(err, req, res, next) {
      ok(req.req);
      ok(res.res);
      ok(err);
      return trace.push(1);
    }).use(function(req, res, next) {
      ok(req.req);
      ok(res.res);
      trace.push(2);
      return 'ok';
    });
    return app.handle(null, {
      req: true
    }, {
      res: true
    }).then(function(res) {
      eq(res, 'ok');
      return eq(trace.length, 2);
    }).then(done).end();
  });
  it('catches passed error with a handler', function(done) {
    var app, trace;
    trace = [];
    app = tell().use(function(req, res, next) {
      return next(new Error('error'));
    })["catch"](function(err, req, res, next) {
      ok(req.req);
      ok(res.res);
      ok(err);
      return trace.push(1);
    }).use(function(req, res, next) {
      ok(req.req);
      ok(res.res);
      trace.push(2);
      return 'ok';
    });
    return app.handle(null, {
      req: true
    }, {
      res: true
    }).then(function(res) {
      eq(res, 'ok');
      return eq(trace.length, 2);
    }).then(done).end();
  });
  it('propagates re-thrown error', function() {
    var app, trace;
    trace = [];
    app = tell().use(function(req, res, next) {
      throw new Error('error');
    })["catch"](function(err, req, res, next) {
      ok(err);
      trace.push(1);
      throw err;
    });
    return throws(Error, function() {
      return app.handle(null, {
        req: true
      }, {
        res: true
      }).fail(function(err) {
        ok(err);
        eq(trace.length, 1);
        throw err;
      }).end();
    });
  });
  it('propagates re-rejected promise', function() {
    var app, trace;
    trace = [];
    app = tell().use(function(req, res, next) {
      return reject(new Error('error'));
    })["catch"](function(err, req, res, next) {
      ok(err);
      trace.push(1);
      return reject(err);
    });
    return throws(Error, function() {
      return app.handle(null, {
        req: true
      }, {
        res: true
      }).fail(function(err) {
        ok(err);
        eq(trace.length, 1);
        throw err;
      }).end();
    });
  });
  it('propagates re-passed error', function() {
    var app, trace;
    trace = [];
    app = tell().use(function(req, res, next) {
      return next(new Error('error'));
    })["catch"](function(err, req, res, next) {
      ok(err);
      trace.push(1);
      return next(err);
    });
    return throws(Error, function() {
      return app.handle(null, {
        req: true
      }, {
        res: true
      }).fail(function(err) {
        ok(err);
        eq(trace.length, 1);
        throw err;
      }).end();
    });
  });
  describe('mounting a handler under a pattern', function() {
    it('responds to exact match', function(done) {
      var app, trace;
      trace = [];
      app = tell().use('/a', function(req, res) {
        eq(req.url, '/');
        return trace.push(1);
      }).use('/b', function(req, res) {
        return trace.push(2);
      }).use(function(req, res) {
        eq(req.url, '/a');
        return trace.push(3);
      });
      return app.handle(null, {
        url: '/a'
      }, {
        res: true
      }).then(function(res) {
        eq(trace.length, 2);
        eq(trace[0], 1);
        return eq(trace[1], 3);
      }).then(done).end();
    });
    it('responds to match of a leading part', function(done) {
      var app, trace;
      trace = [];
      app = tell().use('/a', function(req, res) {
        eq(req.url, '/b');
        return trace.push(1);
      }).use('/b', function(req, res) {
        return trace.push(2);
      }).use(function(req, res) {
        eq(req.url, '/a/b');
        return trace.push(3);
      });
      return app.handle(null, {
        url: '/a/b'
      }, {
        res: true
      }).then(function(res) {
        eq(trace.length, 2);
        eq(trace[0], 1);
        return eq(trace[1], 3);
      }).then(done).end();
    });
    it('does not respond to arbitrary match of a leading part', function(done) {
      var app, trace;
      trace = [];
      app = tell().use('/a', function(req, res) {
        return trace.push(1);
      }).use('/b', function(req, res) {
        return trace.push(2);
      }).use(function(req, res) {
        return trace.push(3);
      });
      return app.handle(null, {
        url: '/ab'
      }, {
        res: true
      }).then(function(res) {
        eq(trace.length, 1);
        return eq(trace[0], 3);
      }).then(done).end();
    });
    return it('does not respond to a no match case', function(done) {
      var app, trace;
      trace = [];
      app = tell().use('/a', function(req, res) {
        return trace.push(1);
      }).use('/b', function(req, res) {
        return trace.push(2);
      }).use(function(req, res) {
        return trace.push(3);
      });
      return app.handle(null, {
        url: '/c'
      }, {
        res: true
      }).then(function(res) {
        eq(trace.length, 1);
        return eq(trace[0], 3);
      }).then(done).end();
    });
  });
  return describe('routing to endpoints', function() {
    return it('routes by method and URI pattern', function(done) {
      var app, trace;
      trace = [];
      app = tell().get('/info', function(req, res) {
        return trace.push(1);
      }).post('/info', function(req, res) {
        return trace.push(2);
      });
      return app.handle(null, {
        url: '/info',
        method: 'POST'
      }, {
        res: true
      }).then(function(res) {
        eq(trace.length, 1);
        return eq(trace[0], 2);
      }).then(done).end();
    });
  });
});
